resources:
  default:
    routes:
      auto: true
  expose:
    entity: ~
    entity2:
      - get: /test/authentication
        handler: handler-example.authenticationResolve
        security: security.rule1
      - get: /test/routing
        handler: handler-example.routingResolve
        security: security.rule1
      - post: /truc/:param
        handler: get.entities
        security: security.rule1
      - get: /test/database
        handler: handler-example.modelResolve
        security: security.rule1
queue:
  listen:
    queueName: hook.service_name.function
